name: Bug report
description: Report a defect in thynkai-core.
labels: ["core", "bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the observed behavior.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps or code snippet.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: e.g. 0.1.0
    validations:
      required: false
