name: Feature request
description: Propose an improvement to the core protocol primitives.
labels: ["core", "discussion"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should change? Keep it precise.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / non-goals
      description: What is explicitly out of scope?
    validations:
      required: false
